-- ============================================================
-- ÇOKLU İŞLETME DEFTERİ (Zeytinkule + Ofisler + İnşaatlar)
-- Bu dosyayı Neon projenizde SQL Editor'e yapıştırıp çalıştırın.
-- ============================================================

drop table if exists staff_payments cascade;
drop table if exists staff cascade;
drop table if exists gelirler cascade;
drop table if exists expenses cascade;
drop table if exists maintenance_items cascade;
drop table if exists payments cascade;
drop table if exists apartments cascade;
drop table if exists settings cascade;
drop table if exists isletmeler cascade;

create table isletmeler (
  id bigint generated by default as identity primary key,
  ad text not null,
  tip text not null check (tip in ('site','genel')),  -- 'site' = Zeytinkule gibi (Daireler var), 'genel' = Ofis/İnşaat (Gelir-Gider var)
  created_at timestamptz default now()
);

create table apartments (
  no integer,
  isletme_id bigint not null references isletmeler(id) on delete cascade,
  kat text,
  malik text,
  net_alan numeric,
  brut_alan numeric,
  ortak_alan numeric,
  toplam_brut_alan numeric,
  durum text not null default 'ev_sahibi' check (durum in ('ev_sahibi','kiraci','bos_odeniyor','bos_muaf')),
  kiraci_adi text,
  primary key (isletme_id, no)
);

create table payments (
  id bigint generated always as identity primary key,
  isletme_id bigint not null references isletmeler(id) on delete cascade,
  apartment_no integer,
  tur text not null check (tur in ('aidat','demirbas')),
  donem text,                 -- aidat icin 'YYYY-MM', demirbas icin 'tek'
  tutar_beklenen numeric,
  tutar_odenen numeric,
  durum text not null default 'ÖDENMEDİ',
  kaynak text,
  not_metni text,
  guncelleme_tarihi timestamptz default now(),
  unique (isletme_id, apartment_no, tur, donem),
  foreign key (isletme_id, apartment_no) references apartments(isletme_id, no) on delete cascade
);

create table maintenance_items (
  id bigint generated always as identity primary key,
  isletme_id bigint not null references isletmeler(id) on delete cascade,
  ad text not null,
  siklik text not null check (siklik in ('aylik','3ayda_bir','yillik')),
  son_yapilma_tarihi date
);

create table expenses (
  id bigint generated always as identity primary key,
  isletme_id bigint not null references isletmeler(id) on delete cascade,
  ay text,
  gider_turu text,
  firma text,
  tutar numeric,
  tarih date,
  durum text default 'ÖDENMEDİ',
  not_metni text,
  bakim_id bigint references maintenance_items(id) on delete set null
);

create table gelirler (
  id bigint generated always as identity primary key,
  isletme_id bigint not null references isletmeler(id) on delete cascade,
  aciklama text,
  tutar numeric,
  tarih date,
  durum text default 'ÖDENMEDİ',
  not_metni text
);

create table staff (
  id bigint generated by default as identity primary key,
  isletme_id bigint not null references isletmeler(id) on delete cascade,
  isim text,
  gorev text,
  aylik_ucret numeric
);

create table staff_payments (
  id bigint generated always as identity primary key,
  staff_id bigint references staff(id) on delete cascade,
  ay text,
  tarih date,
  durum text default 'Bilinmiyor',
  unique (staff_id, ay)
);

create table settings (
  isletme_id bigint not null references isletmeler(id) on delete cascade,
  key text not null,
  value jsonb,
  updated_at timestamptz default now(),
  primary key (isletme_id, key)
);

-- Herkese acik (login'siz) okuma/yazma icin RLS politikalari.
-- NOT: Bu, uygulama linkini + anon key'i bilen HERKESE tam yazma yetkisi verir.
alter table isletmeler enable row level security;
alter table apartments enable row level security;
alter table payments enable row level security;
alter table expenses enable row level security;
alter table maintenance_items enable row level security;
alter table gelirler enable row level security;
alter table staff enable row level security;
alter table staff_payments enable row level security;
alter table settings enable row level security;
create policy "public_all_isletmeler" on isletmeler for all using (true) with check (true);
create policy "public_all_apartments" on apartments for all using (true) with check (true);
create policy "public_all_payments" on payments for all using (true) with check (true);
create policy "public_all_expenses" on expenses for all using (true) with check (true);
create policy "public_all_maintenance_items" on maintenance_items for all using (true) with check (true);
create policy "public_all_gelirler" on gelirler for all using (true) with check (true);
create policy "public_all_staff" on staff for all using (true) with check (true);
create policy "public_all_staff_payments" on staff_payments for all using (true) with check (true);
create policy "public_all_settings" on settings for all using (true) with check (true);

-- İşletmeler
insert into isletmeler (id, ad, tip) values (1, 'Zeytinkule', 'site');
select setval(pg_get_serial_sequence('isletmeler','id'), 1, true);

-- Daireler (Zeytinkule)
insert into apartments (no, isletme_id, kat, malik, net_alan, brut_alan, ortak_alan, toplam_brut_alan, durum, kiraci_adi) values
(1, 1, '1.NORMAL KAT', 'BUSE KAYAN', 66.53, 77.97, 54.2669183546494, 132.236918354649, 'ev_sahibi', NULL),
(2, 1, '1.NORMAL KAT', 'HATUN ERTÜRK', 56.57, 65.9, 45.8662295699807, 111.766229569981, 'ev_sahibi', NULL),
(3, 1, '1.NORMAL KAT', 'ŞÜKRİYE KAHRUMAN', 60.57, 70.03, 48.7406988890098, 118.77069888901, 'ev_sahibi', NULL),
(4, 1, '1.NORMAL KAT', 'OBADA SARY', 67.29, 78.05, 54.3225981477541, 132.372598147754, 'ev_sahibi', NULL),
(5, 1, '1.NORMAL KAT', 'OSMAN KUNDUROĞLU', 41.51, 45.64, 31.7653219662203, 77.4053219662203, 'ev_sahibi', NULL),
(6, 1, '1.NORMAL KAT', 'MUKEL İNŞ. MİM.MÜH. SAN. TİC. LTD.', 39.99, 44.85, 31.2154840093116, 76.0654840093116, 'ev_sahibi', NULL),
(7, 1, '1.NORMAL KAT', 'ŞÜKRİYE KAHRUMAN', 38.79, 44.36, 30.8744452765454, 75.2344452765454, 'ev_sahibi', NULL),
(8, 1, '2.NORMAL KAT', 'MUZAFFER KUNDUROĞLU', 66.53, 77.97, 54.2669183546494, 132.236918354649, 'ev_sahibi', NULL),
(9, 1, '2.NORMAL KAT', 'CENGİZ MUSLU', 56.57, 65.9, 45.8662295699807, 111.766229569981, 'ev_sahibi', NULL),
(10, 1, '2.NORMAL KAT', 'SAMY HAMED', 60.57, 70.03, 48.7406988890098, 118.77069888901, 'ev_sahibi', NULL),
(11, 1, '2.NORMAL KAT', 'MEHMET AKİF GÖZEN', 63.21, 73.66, 51.2671695011347, 124.927169501135, 'ev_sahibi', NULL),
(12, 1, '2.NORMAL KAT', 'DİLFİRE İSA', 63.34, 72.5, 50.4598125011168, 122.959812501117, 'ev_sahibi', NULL),
(13, 1, '2.NORMAL KAT', 'ATİLLA MAKİN', 61.67, 70.85, 49.3114167683328, 120.161416768333, 'ev_sahibi', NULL),
(14, 1, '3.NORMAL KAT', 'MUZAFFER KUNDUROĞLU', 66.6, 77.94, 54.2460384322351, 132.186038432235, 'ev_sahibi', NULL),
(15, 1, '3.NORMAL KAT', 'HAMZA TALAT Ö.(İN. HK. DİLBER ORHAN)', 56.7, 65.9, 45.8662295699807, 111.766229569981, 'ev_sahibi', NULL),
(16, 1, '3.NORMAL KAT', 'GÜLSÜM GÜNEŞ', 60.57, 70.02, 48.7337389148717, 118.753738914872, 'ev_sahibi', NULL),
(17, 1, '3.NORMAL KAT', 'İSMAİL KOL', 63.21, 73.72, 51.3089293459632, 125.028929345963, 'ev_sahibi', NULL),
(18, 1, '3.NORMAL KAT', 'ATİLLA MAKİN', 63.34, 72.5, 50.4598125011168, 122.959812501117, 'ev_sahibi', NULL),
(19, 1, '3.NORMAL KAT', 'AYDIN MAKİN', 61.67, 70.86, 49.3183767424709, 120.178376742471, 'ev_sahibi', NULL),
(20, 1, '4.NORMAL KAT', 'MUZAFFER KUNDUROĞLU', 66.57, 77.97, 54.2669183546494, 132.236918354649, 'ev_sahibi', NULL),
(21, 1, '4.NORMAL KAT', 'ENES ERGİN ', 56.69, 65.9, 45.8662295699807, 111.766229569981, 'ev_sahibi', NULL),
(22, 1, '4.NORMAL KAT', 'OBADA SARY', 60.57, 70.03, 48.7406988890098, 118.77069888901, 'ev_sahibi', NULL),
(23, 1, '4.NORMAL KAT', '1/3 HASAN EDER 1/3 CENGİZ EDER 1/3 METİN EDER', 63.21, 73.72, 51.3089293459632, 125.028929345963, 'ev_sahibi', NULL),
(24, 1, '4.NORMAL KAT', 'AYFER MAKİN', 63.33, 72.5, 50.4598125011168, 122.959812501117, 'ev_sahibi', NULL),
(25, 1, '4.NORMAL KAT', 'FİKRİYE ŞEREFLİ', 61.67, 70.86, 49.3183767424709, 120.178376742471, 'ev_sahibi', NULL),
(26, 1, '5.NORMAL KAT', 'MUZAFFER KUNDUROĞLU', 66.57, 77.97, 54.2669183546494, 132.236918354649, 'ev_sahibi', NULL),
(27, 1, '5.NORMAL KAT', 'BEKİR ÖZTÜRK', 56.69, 65.9, 45.8662295699807, 111.766229569981, 'ev_sahibi', NULL),
(28, 1, '5.NORMAL KAT', 'FİKRİYE ŞEREFLİ', 60.57, 70.03, 48.7406988890098, 118.77069888901, 'ev_sahibi', NULL),
(29, 1, '5.NORMAL KAT', 'LAHİYE AKYÜZ', 63.21, 73.72, 51.3089293459632, 125.028929345963, 'ev_sahibi', NULL),
(30, 1, '5.NORMAL KAT', 'ŞÜKRİYE KAHRUMAN', 63.33, 72.5, 50.4598125011168, 122.959812501117, 'ev_sahibi', NULL),
(31, 1, '5.NORMAL KAT', 'AYDIN MAKİN', 61.67, 70.86, 49.3183767424709, 120.178376742471, 'ev_sahibi', NULL),
(32, 1, '6.NORMAL KAT', 'MELEK KELEŞ', 66.57, 77.97, 54.2669183546494, 132.236918354649, 'ev_sahibi', NULL),
(33, 1, '6.NORMAL KAT', 'SADIK KARAGÖZ', 56.69, 65.9, 45.8662295699807, 111.766229569981, 'ev_sahibi', NULL),
(34, 1, '6.NORMAL KAT', 'TOLGA GÜLER', 60.57, 70.03, 48.7406988890098, 118.77069888901, 'ev_sahibi', NULL),
(35, 1, '6.NORMAL KAT', 'NECMETTİN ÇOKA', 63.21, 73.72, 51.3089293459632, 125.028929345963, 'ev_sahibi', NULL),
(36, 1, '6.NORMAL KAT', 'SADIK KARAGÖZ', 63.33, 72.5, 50.4598125011168, 122.959812501117, 'ev_sahibi', NULL),
(37, 1, '6.NORMAL KAT', 'ATİLLA MAKİN', 61.67, 70.86, 49.3183767424709, 120.178376742471, 'ev_sahibi', NULL),
(38, 1, '7.NORMAL KAT', 'HODA İZZATULLAH', 74, 86.61, 60.2803360099549, 146.890336009955, 'ev_sahibi', NULL),
(39, 1, '7.NORMAL KAT', 'FUAT TAŞÇI', 73.84, 85.42, 59.4520990875228, 144.872099087523, 'ev_sahibi', NULL),
(40, 1, '7.NORMAL KAT', 'AMEENA İZZATULLAH', 37.78, 44.11, 30.7004459230933, 74.8104459230933, 'ev_sahibi', NULL),
(41, 1, '7.NORMAL KAT', 'ETEM BEĞ GENCEBAĞ', 63.27, 73.72, 51.3089293459632, 125.028929345963, 'ev_sahibi', NULL),
(42, 1, '7.NORMAL KAT', 'ZEKERİYA OĞUZ', 63.38, 72.5, 50.4598125011168, 122.959812501117, 'ev_sahibi', NULL),
(43, 1, '7.NORMAL KAT', 'MURAT KELEŞ', 61.69, 70.86, 49.3183767424709, 120.178376742471, 'ev_sahibi', NULL),
(44, 1, '8.NORMAL KAT', 'İZZATULLAH FAHD', 66.57, 77.97, 54.2669183546494, 132.236918354649, 'ev_sahibi', NULL),
(45, 1, '8.NORMAL KAT', 'CENGİZ MUSLU', 56.57, 65.83, 45.8175097510141, 111.647509751014, 'ev_sahibi', NULL),
(46, 1, '8.NORMAL KAT', 'ENES GÜRLÜ', 60.56, 70.03, 48.7406988890098, 118.77069888901, 'ev_sahibi', NULL),
(47, 1, '8.NORMAL KAT', 'HÜSEYİN DİNLER', 63.3, 73.71, 51.3019693718251, 125.011969371825, 'ev_sahibi', NULL),
(48, 1, '8.NORMAL KAT', 'NAZMİYE MUSLU', 63.39, 72.5, 50.4598125011168, 122.959812501117, 'ev_sahibi', NULL),
(49, 1, '8.NORMAL KAT', 'CENGİZ MUSLU', 61.66, 70.86, 49.3183767424709, 120.178376742471, 'ev_sahibi', NULL),
(50, 1, '9.NORMAL KAT', 'İZZATULLAH FAHD', 66.57, 77.97, 54.2669183546494, 132.236918354649, 'ev_sahibi', NULL),
(51, 1, '9.NORMAL KAT', 'HÜSEYİN DİNLER', 56.57, 65.83, 45.8175097510141, 111.647509751014, 'ev_sahibi', NULL),
(52, 1, '9.NORMAL KAT', 'BARIŞ HATUNOĞLU', 60.56, 70.03, 48.7406988890098, 118.77069888901, 'ev_sahibi', NULL),
(53, 1, '9.NORMAL KAT', 'MURAT KELEŞ', 63.3, 73.71, 51.3019693718251, 125.011969371825, 'ev_sahibi', NULL),
(54, 1, '9.NORMAL KAT', 'HODA İZZATULLAH', 63.39, 72.5, 50.4598125011168, 122.959812501117, 'ev_sahibi', NULL),
(55, 1, '9.NORMAL KAT', 'MAHSUN GETİREN', 61.66, 70.86, 49.3183767424709, 120.178376742471, 'ev_sahibi', NULL),
(56, 1, '10.NORMAL KAT', 'SULAIMAN MOHIBULLLAH', 90, 106, 73.7757258637019, 179.775725863702, 'ev_sahibi', NULL),
(57, 1, '10.NORMAL KAT', 'MUHAMMED DOĞAN VURGUN', 95.26, 111.1, 77.3253126741252, 188.425312674125, 'ev_sahibi', NULL),
(58, 1, '10.NORMAL KAT', 'NİBRAS FAKHIR', 91.45, 107.08, 74.527403070615, 181.607403070615, 'ev_sahibi', NULL),
(59, 1, '10.NORMAL KAT', NULL, 96.12, 113.08, 78.7033875534661, 191.783387553466, 'ev_sahibi', NULL),
(60, 1, '11.NORMAL KAT', 'ZHONG WİE', 90, 106, 73.7757258637019, 179.775725863702, 'ev_sahibi', NULL),
(61, 1, '11.NORMAL KAT', 'FULYA UYGUR', 95.26, 111.1, 77.3253126741252, 188.425312674125, 'ev_sahibi', NULL),
(62, 1, '11.NORMAL KAT', 'MOHAMMED JALIL POUR SAMARİN', 91.45, 107.08, 74.527403070615, 181.607403070615, 'ev_sahibi', NULL),
(63, 1, '11.NORMAL KAT', 'SOUAD RABİAH GHANEM', 96.12, 113.08, 78.7033875534661, 191.783387553466, 'ev_sahibi', NULL),
(64, 1, '12.NORMAL KAT', 'SALİH TİRYAKİ', 90, 106, 73.7757258637019, 179.775725863702, 'ev_sahibi', NULL),
(65, 1, '12.NORMAL KAT', 'MUKEL İNŞ. MİM.MÜH. SAN. TİC. LTD. ŞTİ', 95.26, 111.1, 77.3253126741252, 188.425312674125, 'ev_sahibi', NULL),
(66, 1, '12.NORMAL KAT', 'MEHMET CAN KURAY', 91.45, 107.08, 74.527403070615, 181.607403070615, 'ev_sahibi', NULL),
(67, 1, '12.NORMAL KAT', 'FUAD AHMET ABDULLAH', 96.12, 113.08, 78.7033875534661, 191.783387553466, 'ev_sahibi', NULL),
(68, 1, '13.NORMAL KAT', 'AMEENA İZZATULLAH', 66.15, 77.91, 54.2251585098209, 132.135158509821, 'ev_sahibi', NULL),
(69, 1, '13.NORMAL KAT', 'MUKEL İNŞ. MİM.MÜH. SAN. TİC. LTD. ŞTİ', 102.67, 117.58, 81.8353759156044, 199.415375915604, 'ev_sahibi', NULL),
(70, 1, '13.NORMAL KAT', 'BARIŞ HATUNOĞLU', 104.89, 121.33, 84.4453662173863, 205.775366217386, 'ev_sahibi', NULL),
(71, 1, '13.NORMAL KAT', 'MUKEL İNŞ. MİM.MÜH. SAN. TİC. LTD. ŞTİ', 96.07, 113.08, 78.7033875534661, 191.783387553466, 'ev_sahibi', NULL);

-- Demirbaş ödemeleri
insert into payments (isletme_id, apartment_no, tur, donem, tutar_beklenen, tutar_odenen, durum, kaynak, not_metni) values
(1, 1, 'demirbas', 'tek', 10000, NULL, 'ÖDENMEDİ', '-', NULL),
(1, 2, 'demirbas', 'tek', 10000, NULL, 'ÖDENMEDİ', '-', NULL),
(1, 3, 'demirbas', 'tek', 10000, NULL, 'ÖDENMEDİ', '-', NULL),
(1, 4, 'demirbas', 'tek', 10000, NULL, 'ÖDENDİ', 'Defter - kontrol edilmeli', 'Tutar deftere yazılmamış, Excel’e girilmedi'),
(1, 5, 'demirbas', 'tek', 10000, NULL, 'ÖDENMEDİ', '-', NULL),
(1, 6, 'demirbas', 'tek', 10000, 10000, 'ÖDENDİ', 'Dijital kayıt', NULL),
(1, 7, 'demirbas', 'tek', 10000, NULL, 'ÖDENMEDİ', '-', NULL),
(1, 8, 'demirbas', 'tek', 10000, NULL, 'ÖDENMEDİ', '-', NULL),
(1, 9, 'demirbas', 'tek', 10000, NULL, 'ÖDENMEDİ', '-', NULL),
(1, 10, 'demirbas', 'tek', 10000, NULL, 'ÖDENMEDİ', '-', NULL),
(1, 11, 'demirbas', 'tek', 10000, NULL, 'ÖDENDİ', 'Defter - kontrol edilmeli', 'Tutar deftere yazılmamış, Excel’e girilmedi'),
(1, 12, 'demirbas', 'tek', 10000, 10000, 'ÖDENDİ', 'Dijital kayıt', NULL),
(1, 13, 'demirbas', 'tek', 10000, NULL, 'ÖDENDİ', 'Defter - kontrol edilmeli', 'Tutar deftere yazılmamış, Excel’e girilmedi'),
(1, 14, 'demirbas', 'tek', 10000, NULL, 'ÖDENDİ', 'Defter - kontrol edilmeli', 'Tutar deftere yazılmamış, Excel’e girilmedi'),
(1, 15, 'demirbas', 'tek', 10000, 10000, 'ÖDENDİ', 'Dijital kayıt', NULL),
(1, 16, 'demirbas', 'tek', 10000, 10000, 'ÖDENDİ', 'Dijital kayıt', NULL),
(1, 17, 'demirbas', 'tek', 10000, NULL, 'ÖDENDİ', 'Defter - kontrol edilmeli', 'Tutar deftere yazılmamış, Excel’e girilmedi'),
(1, 18, 'demirbas', 'tek', 10000, NULL, 'ÖDENDİ', 'Defter - kontrol edilmeli', 'Tutar deftere yazılmamış, Excel’e girilmedi'),
(1, 19, 'demirbas', 'tek', 10000, 10000, 'ÖDENDİ', 'Dijital kayıt', NULL),
(1, 20, 'demirbas', 'tek', 10000, NULL, 'ÖDENDİ', 'Defter - kontrol edilmeli', 'Tutar deftere yazılmamış, Excel’e girilmedi'),
(1, 21, 'demirbas', 'tek', 10000, 10000, 'ÖDENDİ', 'Dijital kayıt', NULL),
(1, 22, 'demirbas', 'tek', 10000, NULL, 'ÖDENDİ', 'Defter - kontrol edilmeli', 'Tutar deftere yazılmamış, Excel’e girilmedi'),
(1, 23, 'demirbas', 'tek', 10000, NULL, 'ÖDENDİ', 'Defter - kontrol edilmeli', 'Tutar deftere yazılmamış, Excel’e girilmedi'),
(1, 24, 'demirbas', 'tek', 10000, 10000, 'ÖDENDİ', 'Dijital kayıt', NULL),
(1, 25, 'demirbas', 'tek', 10000, 10000, 'ÖDENDİ', 'Dijital kayıt', NULL),
(1, 26, 'demirbas', 'tek', 10000, NULL, 'ÖDENMEDİ', '-', NULL),
(1, 27, 'demirbas', 'tek', 10000, 7000, 'KISMİ ÖDENDİ', 'Dijital kayıt', '3,000 ₺ kalan bakiye var (defterde de kısmi ödeme notu var)'),
(1, 28, 'demirbas', 'tek', 10000, 10000, 'ÖDENDİ', 'Dijital kayıt', NULL),
(1, 29, 'demirbas', 'tek', 10000, NULL, 'ÖDENMEDİ', '-', NULL),
(1, 30, 'demirbas', 'tek', 10000, 10000, 'ÖDENDİ', 'Dijital kayıt', NULL),
(1, 31, 'demirbas', 'tek', 10000, 10000, 'ÖDENDİ', 'Dijital kayıt', NULL),
(1, 32, 'demirbas', 'tek', 10000, NULL, 'ÖDENMEDİ', '-', NULL),
(1, 33, 'demirbas', 'tek', 10000, 10000, 'ÖDENDİ', 'Dijital kayıt', NULL),
(1, 34, 'demirbas', 'tek', 10000, NULL, 'ÖDENMEDİ', '-', NULL),
(1, 35, 'demirbas', 'tek', 10000, NULL, 'ÖDENMEDİ', '-', NULL),
(1, 36, 'demirbas', 'tek', 10000, 10000, 'ÖDENDİ', 'Dijital kayıt', NULL),
(1, 37, 'demirbas', 'tek', 10000, NULL, 'ÖDENDİ', 'Defter - kontrol edilmeli', 'Tutar deftere yazılmamış, Excel’e girilmedi'),
(1, 38, 'demirbas', 'tek', 10000, NULL, 'ÖDENMEDİ', '-', NULL),
(1, 39, 'demirbas', 'tek', 10000, 10000, 'ÖDENDİ', 'Dijital kayıt', NULL),
(1, 40, 'demirbas', 'tek', 10000, NULL, 'ÖDENMEDİ', '-', NULL),
(1, 41, 'demirbas', 'tek', 10000, NULL, 'ÖDENDİ', 'Defter - kontrol edilmeli', 'Tutar deftere yazılmamış, Excel’e girilmedi'),
(1, 42, 'demirbas', 'tek', 10000, 10000, 'ÖDENDİ', 'Dijital kayıt', NULL),
(1, 43, 'demirbas', 'tek', 10000, 10000, 'ÖDENDİ', 'Dijital kayıt', NULL),
(1, 44, 'demirbas', 'tek', 10000, NULL, 'ÖDENMEDİ', '-', NULL),
(1, 45, 'demirbas', 'tek', 10000, NULL, 'ÖDENMEDİ', '-', NULL),
(1, 46, 'demirbas', 'tek', 10000, NULL, 'ÖDENMEDİ', '-', NULL),
(1, 47, 'demirbas', 'tek', 10000, NULL, 'ÖDENMEDİ', '-', NULL),
(1, 48, 'demirbas', 'tek', 10000, NULL, 'ÖDENMEDİ', '-', NULL),
(1, 49, 'demirbas', 'tek', 10000, NULL, 'ÖDENMEDİ', '-', NULL),
(1, 50, 'demirbas', 'tek', 10000, NULL, 'ÖDENMEDİ', '-', NULL),
(1, 51, 'demirbas', 'tek', 10000, NULL, 'ÖDENDİ', 'Defter - kontrol edilmeli', 'Tutar deftere yazılmamış, Excel’e girilmedi'),
(1, 52, 'demirbas', 'tek', 10000, 10000, 'ÖDENDİ', 'Dijital kayıt', NULL),
(1, 53, 'demirbas', 'tek', 10000, NULL, 'ÖDENMEDİ', '-', NULL),
(1, 54, 'demirbas', 'tek', 10000, NULL, 'ÖDENMEDİ', '-', NULL),
(1, 55, 'demirbas', 'tek', 10000, NULL, 'ÖDENMEDİ', '-', NULL),
(1, 56, 'demirbas', 'tek', 10000, NULL, 'ÖDENDİ', 'Defter - kontrol edilmeli', 'Tutar deftere yazılmamış, Excel’e girilmedi'),
(1, 57, 'demirbas', 'tek', 10000, 10000, 'ÖDENDİ', 'Dijital kayıt', NULL),
(1, 58, 'demirbas', 'tek', 10000, 10000, 'ÖDENDİ', 'Dijital kayıt', NULL),
(1, 59, 'demirbas', 'tek', 10000, NULL, 'ÖDENDİ', 'Defter - kontrol edilmeli', 'Tutar deftere yazılmamış, Excel’e girilmedi'),
(1, 60, 'demirbas', 'tek', 10000, 10000, 'ÖDENDİ', 'Dijital kayıt', NULL),
(1, 61, 'demirbas', 'tek', 10000, 10000, 'ÖDENDİ', 'Dijital kayıt', NULL),
(1, 62, 'demirbas', 'tek', 10000, NULL, 'KONTROL EDİLSİN', 'Defter (karalama/düzeltme var)', 'Defterde bu satırda karalama var, fiziksel deftere bakılmalı'),
(1, 63, 'demirbas', 'tek', 10000, NULL, 'ÖDENDİ', 'Defter - kontrol edilmeli', 'Tutar deftere yazılmamış, Excel’e girilmedi'),
(1, 64, 'demirbas', 'tek', 10000, 10000, 'ÖDENDİ', 'Dijital kayıt', NULL),
(1, 65, 'demirbas', 'tek', 10000, 10000, 'ÖDENDİ', 'Dijital kayıt', NULL),
(1, 66, 'demirbas', 'tek', 10000, 10000, 'ÖDENDİ', 'Dijital kayıt', NULL),
(1, 67, 'demirbas', 'tek', 10000, NULL, 'ÖDENMEDİ', '-', NULL),
(1, 68, 'demirbas', 'tek', 10000, NULL, 'ÖDENMEDİ', '-', NULL),
(1, 69, 'demirbas', 'tek', 10000, 10000, 'ÖDENDİ', 'Dijital kayıt', NULL),
(1, 70, 'demirbas', 'tek', 10000, 10000, 'ÖDENDİ', 'Dijital kayıt', NULL),
(1, 71, 'demirbas', 'tek', 10000, NULL, 'ÖDENDİ', 'Defter - kontrol edilmeli', 'Tutar deftere yazılmamış, Excel’e girilmedi');

-- Aidat ödemeleri 2026-06
insert into payments (isletme_id, apartment_no, tur, donem, tutar_odenen, durum, kaynak, not_metni) values
(1, 1, 'aidat', '2026-06', 5594, 'ÖDENDİ', 'Dijital kayıt', NULL),
(1, 2, 'aidat', '2026-06', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 3, 'aidat', '2026-06', NULL, 'ÖDENDİ', 'Defter - kontrol edilmeli', 'Tutar deftere yazılmamış'),
(1, 4, 'aidat', '2026-06', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 5, 'aidat', '2026-06', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 6, 'aidat', '2026-06', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 7, 'aidat', '2026-06', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 8, 'aidat', '2026-06', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 9, 'aidat', '2026-06', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 10, 'aidat', '2026-06', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 11, 'aidat', '2026-06', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 12, 'aidat', '2026-06', NULL, 'ÖDENDİ', 'Defter - kontrol edilmeli', 'Tutar deftere yazılmamış'),
(1, 13, 'aidat', '2026-06', NULL, 'ÖDENDİ', 'Defter - kontrol edilmeli', 'Tutar deftere yazılmamış'),
(1, 14, 'aidat', '2026-06', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 15, 'aidat', '2026-06', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 16, 'aidat', '2026-06', 7840, 'ÖDENDİ', 'Dijital kayıt', NULL),
(1, 17, 'aidat', '2026-06', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 18, 'aidat', '2026-06', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 19, 'aidat', '2026-06', NULL, 'ÖDENDİ (?)', 'Defter - düzeltme izi var', 'Defterde bu hücre üzerinde düzeltme/karalama var'),
(1, 20, 'aidat', '2026-06', NULL, 'ÖDENDİ', 'Defter - kontrol edilmeli', 'Tutar deftere yazılmamış'),
(1, 21, 'aidat', '2026-06', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 22, 'aidat', '2026-06', NULL, 'ÖDENDİ', 'Defter - kontrol edilmeli', 'Tutar deftere yazılmamış'),
(1, 23, 'aidat', '2026-06', NULL, 'ÖDENDİ', 'Defter - kontrol edilmeli', 'Tutar deftere yazılmamış'),
(1, 24, 'aidat', '2026-06', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 25, 'aidat', '2026-06', NULL, 'ÖDENDİ (?)', 'Defter - düşük güven', 'İşaret soluk/belirsiz, deftere bakılıp teyit edilmeli'),
(1, 26, 'aidat', '2026-06', NULL, 'ÖDENDİ', 'Defter - kontrol edilmeli', 'Tutar deftere yazılmamış'),
(1, 27, 'aidat', '2026-06', 4700, 'ÖDENDİ', 'Dijital kayıt', NULL),
(1, 28, 'aidat', '2026-06', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 29, 'aidat', '2026-06', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 30, 'aidat', '2026-06', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 31, 'aidat', '2026-06', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 32, 'aidat', '2026-06', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 33, 'aidat', '2026-06', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 34, 'aidat', '2026-06', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 35, 'aidat', '2026-06', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 36, 'aidat', '2026-06', 5202, 'ÖDENDİ', 'Dijital kayıt', NULL),
(1, 37, 'aidat', '2026-06', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 38, 'aidat', '2026-06', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 39, 'aidat', '2026-06', 6127.5, 'ÖDENDİ', 'Dijital kayıt', NULL),
(1, 40, 'aidat', '2026-06', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 41, 'aidat', '2026-06', NULL, 'ÖDENDİ', 'Defter - kontrol edilmeli', 'Tutar deftere yazılmamış'),
(1, 42, 'aidat', '2026-06', 5201, 'ÖDENDİ', 'Dijital kayıt', NULL),
(1, 43, 'aidat', '2026-06', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 44, 'aidat', '2026-06', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 45, 'aidat', '2026-06', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 46, 'aidat', '2026-06', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 47, 'aidat', '2026-06', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 48, 'aidat', '2026-06', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 49, 'aidat', '2026-06', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 50, 'aidat', '2026-06', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 51, 'aidat', '2026-06', NULL, 'ÖDENDİ', 'Defter - kontrol edilmeli', 'Tutar deftere yazılmamış'),
(1, 52, 'aidat', '2026-06', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 53, 'aidat', '2026-06', 5287.92, 'ÖDENDİ', 'Dijital kayıt', NULL),
(1, 54, 'aidat', '2026-06', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 55, 'aidat', '2026-06', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 56, 'aidat', '2026-06', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 57, 'aidat', '2026-06', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 58, 'aidat', '2026-06', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 59, 'aidat', '2026-06', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 60, 'aidat', '2026-06', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 61, 'aidat', '2026-06', NULL, 'ÖDENDİ', 'Defter - kontrol edilmeli', 'Tutar deftere yazılmamış'),
(1, 62, 'aidat', '2026-06', NULL, 'KONTROL EDİLSİN', 'Defter (karalama/düzeltme var)', 'Defterde bu satırda karalama var, fiziksel deftere bakılmalı'),
(1, 63, 'aidat', '2026-06', NULL, 'ÖDENDİ', 'Defter - kontrol edilmeli', 'Tutar deftere yazılmamış'),
(1, 64, 'aidat', '2026-06', 7605, 'ÖDENDİ', 'Dijital kayıt', NULL),
(1, 65, 'aidat', '2026-06', 7682, 'ÖDENDİ', 'Dijital kayıt', NULL),
(1, 66, 'aidat', '2026-06', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 67, 'aidat', '2026-06', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 68, 'aidat', '2026-06', NULL, 'VERMİYOR', 'Defter', 'Defterde bu ay için ''VERMİYOR'' notu var — ödemeyi reddediyor'),
(1, 69, 'aidat', '2026-06', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 70, 'aidat', '2026-06', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 71, 'aidat', '2026-06', NULL, 'ÖDENMEDİ', '-', NULL);

-- Aidat ödemeleri 2026-07
insert into payments (isletme_id, apartment_no, tur, donem, tutar_odenen, durum, kaynak, not_metni) values
(1, 1, 'aidat', '2026-07', NULL, 'ÖDENDİ', 'Defter - kontrol edilmeli', 'Tutar deftere yazılmamış'),
(1, 2, 'aidat', '2026-07', NULL, 'ÖDENDİ', 'Defter - kontrol edilmeli', 'Tutar deftere yazılmamış'),
(1, 3, 'aidat', '2026-07', NULL, 'ÖDENDİ', 'Defter - kontrol edilmeli', 'Tutar deftere yazılmamış'),
(1, 4, 'aidat', '2026-07', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 5, 'aidat', '2026-07', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 6, 'aidat', '2026-07', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 7, 'aidat', '2026-07', NULL, 'ÖDENDİ (?)', 'Defter - düşük güven', 'İşaret soluk/belirsiz, deftere bakılıp teyit edilmeli'),
(1, 8, 'aidat', '2026-07', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 9, 'aidat', '2026-07', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 10, 'aidat', '2026-07', NULL, 'ÖDENDİ', 'Defter - kontrol edilmeli', 'Tutar deftere yazılmamış'),
(1, 11, 'aidat', '2026-07', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 12, 'aidat', '2026-07', NULL, 'ÖDENDİ', 'Defter - kontrol edilmeli', 'Tutar deftere yazılmamış'),
(1, 13, 'aidat', '2026-07', NULL, 'ÖDENDİ', 'Defter - kontrol edilmeli', 'Tutar deftere yazılmamış'),
(1, 14, 'aidat', '2026-07', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 15, 'aidat', '2026-07', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 16, 'aidat', '2026-07', NULL, 'ÖDENDİ', 'Defter - kontrol edilmeli', 'Tutar deftere yazılmamış'),
(1, 17, 'aidat', '2026-07', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 18, 'aidat', '2026-07', NULL, 'ÖDENDİ (?)', 'Defter - düşük güven', 'İşaret soluk/belirsiz, deftere bakılıp teyit edilmeli'),
(1, 19, 'aidat', '2026-07', NULL, 'ÖDENDİ', 'Defter - kontrol edilmeli', 'Tutar deftere yazılmamış'),
(1, 20, 'aidat', '2026-07', NULL, 'ÖDENDİ', 'Defter - kontrol edilmeli', 'Tutar deftere yazılmamış'),
(1, 21, 'aidat', '2026-07', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 22, 'aidat', '2026-07', NULL, 'ÖDENDİ', 'Defter - kontrol edilmeli', 'Tutar deftere yazılmamış'),
(1, 23, 'aidat', '2026-07', NULL, 'ÖDENDİ', 'Defter - kontrol edilmeli', 'Tutar deftere yazılmamış'),
(1, 24, 'aidat', '2026-07', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 25, 'aidat', '2026-07', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 26, 'aidat', '2026-07', NULL, 'ÖDENDİ', 'Defter - kontrol edilmeli', 'Tutar deftere yazılmamış'),
(1, 27, 'aidat', '2026-07', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 28, 'aidat', '2026-07', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 29, 'aidat', '2026-07', NULL, 'ÖDENDİ', 'Defter - kontrol edilmeli', 'Tutar deftere yazılmamış'),
(1, 30, 'aidat', '2026-07', NULL, 'ÖDENDİ', 'Defter - kontrol edilmeli', 'Tutar deftere yazılmamış'),
(1, 31, 'aidat', '2026-07', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 32, 'aidat', '2026-07', NULL, 'ÖDENDİ', 'Defter - kontrol edilmeli', 'Tutar deftere yazılmamış'),
(1, 33, 'aidat', '2026-07', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 34, 'aidat', '2026-07', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 35, 'aidat', '2026-07', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 36, 'aidat', '2026-07', NULL, 'ÖDENDİ', 'Defter - kontrol edilmeli', 'Tutar deftere yazılmamış'),
(1, 37, 'aidat', '2026-07', NULL, 'ÖDENDİ (?)', 'Defter - düşük güven', 'İşaret soluk/belirsiz, deftere bakılıp teyit edilmeli'),
(1, 38, 'aidat', '2026-07', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 39, 'aidat', '2026-07', NULL, 'ÖDENDİ', 'Defter - kontrol edilmeli', 'Tutar deftere yazılmamış'),
(1, 40, 'aidat', '2026-07', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 41, 'aidat', '2026-07', NULL, 'ÖDENDİ', 'Defter - kontrol edilmeli', 'Tutar deftere yazılmamış'),
(1, 42, 'aidat', '2026-07', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 43, 'aidat', '2026-07', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 44, 'aidat', '2026-07', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 45, 'aidat', '2026-07', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 46, 'aidat', '2026-07', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 47, 'aidat', '2026-07', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 48, 'aidat', '2026-07', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 49, 'aidat', '2026-07', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 50, 'aidat', '2026-07', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 51, 'aidat', '2026-07', NULL, 'ÖDENDİ', 'Defter - kontrol edilmeli', 'Tutar deftere yazılmamış'),
(1, 52, 'aidat', '2026-07', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 53, 'aidat', '2026-07', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 54, 'aidat', '2026-07', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 55, 'aidat', '2026-07', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 56, 'aidat', '2026-07', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 57, 'aidat', '2026-07', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 58, 'aidat', '2026-07', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 59, 'aidat', '2026-07', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 60, 'aidat', '2026-07', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 61, 'aidat', '2026-07', NULL, 'ÖDENDİ', 'Defter - kontrol edilmeli', 'Tutar deftere yazılmamış'),
(1, 62, 'aidat', '2026-07', NULL, 'KONTROL EDİLSİN', 'Defter (karalama/düzeltme var)', 'Defterde bu satırda karalama var, fiziksel deftere bakılmalı'),
(1, 63, 'aidat', '2026-07', NULL, 'ÖDENDİ', 'Defter - kontrol edilmeli', 'Tutar deftere yazılmamış'),
(1, 64, 'aidat', '2026-07', NULL, 'ÖDENDİ', 'Defter - kontrol edilmeli', 'Tutar deftere yazılmamış'),
(1, 65, 'aidat', '2026-07', NULL, 'ÖDENDİ', 'Defter - kontrol edilmeli', 'Tutar deftere yazılmamış'),
(1, 66, 'aidat', '2026-07', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 67, 'aidat', '2026-07', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 68, 'aidat', '2026-07', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 69, 'aidat', '2026-07', NULL, 'ÖDENDİ', 'Defter - kontrol edilmeli', 'Tutar deftere yazılmamış'),
(1, 70, 'aidat', '2026-07', NULL, 'ÖDENDİ (?)', 'Defter - düşük güven', 'İşaret soluk/belirsiz, deftere bakılıp teyit edilmeli'),
(1, 71, 'aidat', '2026-07', NULL, 'ÖDENMEDİ', '-', NULL);

-- Aidat ödemeleri 2026-08
insert into payments (isletme_id, apartment_no, tur, donem, tutar_odenen, durum, kaynak, not_metni) values
(1, 1, 'aidat', '2026-08', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 2, 'aidat', '2026-08', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 3, 'aidat', '2026-08', NULL, 'ÖDENDİ', 'Defter - kontrol edilmeli', 'Tutar deftere yazılmamış'),
(1, 4, 'aidat', '2026-08', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 5, 'aidat', '2026-08', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 6, 'aidat', '2026-08', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 7, 'aidat', '2026-08', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 8, 'aidat', '2026-08', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 9, 'aidat', '2026-08', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 10, 'aidat', '2026-08', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 11, 'aidat', '2026-08', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 12, 'aidat', '2026-08', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 13, 'aidat', '2026-08', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 14, 'aidat', '2026-08', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 15, 'aidat', '2026-08', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 16, 'aidat', '2026-08', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 17, 'aidat', '2026-08', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 18, 'aidat', '2026-08', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 19, 'aidat', '2026-08', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 20, 'aidat', '2026-08', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 21, 'aidat', '2026-08', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 22, 'aidat', '2026-08', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 23, 'aidat', '2026-08', NULL, 'ÖDENDİ (?)', 'Defter - düşük güven', 'İşaret soluk/belirsiz, deftere bakılıp teyit edilmeli'),
(1, 24, 'aidat', '2026-08', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 25, 'aidat', '2026-08', NULL, 'ÖDENDİ (?)', 'Defter - düşük güven', 'İşaret soluk/belirsiz, deftere bakılıp teyit edilmeli'),
(1, 26, 'aidat', '2026-08', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 27, 'aidat', '2026-08', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 28, 'aidat', '2026-08', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 29, 'aidat', '2026-08', NULL, 'ÖDENDİ', 'Defter - kontrol edilmeli', 'Tutar deftere yazılmamış'),
(1, 30, 'aidat', '2026-08', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 31, 'aidat', '2026-08', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 32, 'aidat', '2026-08', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 33, 'aidat', '2026-08', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 34, 'aidat', '2026-08', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 35, 'aidat', '2026-08', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 36, 'aidat', '2026-08', NULL, 'ÖDENDİ', 'Defter - kontrol edilmeli', 'Tutar deftere yazılmamış'),
(1, 37, 'aidat', '2026-08', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 38, 'aidat', '2026-08', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 39, 'aidat', '2026-08', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 40, 'aidat', '2026-08', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 41, 'aidat', '2026-08', NULL, 'ÖDENDİ', 'Defter - kontrol edilmeli', 'Tutar deftere yazılmamış'),
(1, 42, 'aidat', '2026-08', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 43, 'aidat', '2026-08', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 44, 'aidat', '2026-08', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 45, 'aidat', '2026-08', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 46, 'aidat', '2026-08', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 47, 'aidat', '2026-08', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 48, 'aidat', '2026-08', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 49, 'aidat', '2026-08', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 50, 'aidat', '2026-08', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 51, 'aidat', '2026-08', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 52, 'aidat', '2026-08', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 53, 'aidat', '2026-08', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 54, 'aidat', '2026-08', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 55, 'aidat', '2026-08', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 56, 'aidat', '2026-08', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 57, 'aidat', '2026-08', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 58, 'aidat', '2026-08', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 59, 'aidat', '2026-08', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 60, 'aidat', '2026-08', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 61, 'aidat', '2026-08', NULL, 'ÖDENDİ', 'Defter - kontrol edilmeli', 'Tutar deftere yazılmamış'),
(1, 62, 'aidat', '2026-08', NULL, 'KONTROL EDİLSİN', 'Defter (karalama/düzeltme var)', 'Defterde bu satırda karalama var, fiziksel deftere bakılmalı'),
(1, 63, 'aidat', '2026-08', NULL, 'ÖDENDİ', 'Defter - kontrol edilmeli', 'Tutar deftere yazılmamış'),
(1, 64, 'aidat', '2026-08', NULL, 'ÖDENDİ', 'Defter - kontrol edilmeli', 'Tutar deftere yazılmamış'),
(1, 65, 'aidat', '2026-08', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 66, 'aidat', '2026-08', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 67, 'aidat', '2026-08', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 68, 'aidat', '2026-08', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 69, 'aidat', '2026-08', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 70, 'aidat', '2026-08', NULL, 'ÖDENMEDİ', '-', NULL),
(1, 71, 'aidat', '2026-08', NULL, 'ÖDENMEDİ', '-', NULL);

-- Fatura / sabit giderler (Zeytinkule)
insert into expenses (isletme_id, ay, gider_turu, firma, tutar, tarih, durum, not_metni) values
(1, 'OCAK', 'Asansör ve Mekanik', 'Hyundai (Sözleşme: Ocak 2026/2027)', 22500, '2026-01-01', 'ÖDENDİ', 'Yıllık bakım sözleşmesi'),
(1, 'MART', 'Yönetim ve Resmi İşler', 'Noter', 1227.61, '2026-03-25', 'ÖDENDİ', 'Karar Defteri'),
(1, 'MART-NİSAN-MAYIS', 'Danışmanlık Hizmeti', NULL, 380835, '2026-06-03', 'ÖDENDİ', '3 aylık toplu ödeme'),
(1, 'HAZİRAN', 'Elektrik ve Enerji', 'CK Boğaziçi Elektrik', 23149.44, '2026-06-10', 'ÖDENDİ', 'Abone No: 2955187859'),
(1, 'HAZİRAN', 'Elektrik ve Enerji', 'CK Boğaziçi Elektrik', 11710.27, '2026-06-22', 'ÖDENDİ', NULL),
(1, 'TEMMUZ', 'Elektrik ve Enerji', NULL, NULL, NULL, 'ÖDENMEDİ', NULL),
(1, 'TEMMUZ', 'Su', NULL, NULL, NULL, 'ÖDENMEDİ', NULL),
(1, 'TEMMUZ', 'Doğalgaz', NULL, NULL, NULL, 'ÖDENMEDİ', NULL),
(1, 'TEMMUZ', 'İnternet', NULL, NULL, NULL, 'ÖDENMEDİ', NULL),
(1, 'TEMMUZ', 'Asansör ve Mekanik', NULL, NULL, NULL, 'ÖDENMEDİ', NULL),
(1, 'TEMMUZ', 'Çevre ve Temizlik', NULL, NULL, NULL, 'ÖDENMEDİ', NULL),
(1, 'TEMMUZ', 'Otopark ve Bariyer', NULL, NULL, NULL, 'ÖDENMEDİ', NULL),
(1, 'TEMMUZ', 'Kamera ve Güvenlik Sistemleri', NULL, NULL, NULL, 'ÖDENMEDİ', NULL),
(1, 'TEMMUZ', 'Yangın ve Güvenlik', NULL, NULL, NULL, 'ÖDENMEDİ', NULL),
(1, 'TEMMUZ', 'Bakım ve Arıza Fonu', NULL, NULL, NULL, 'ÖDENMEDİ', NULL),
(1, 'TEMMUZ', 'Yönetim ve Resmi İşler', NULL, NULL, NULL, 'ÖDENMEDİ', NULL),
(1, 'TEMMUZ', 'İlaçlama', NULL, 8000, NULL, 'ÖDENDİ', NULL),
(1, 'TEMMUZ', '(belirtilmemiş)', NULL, 22000, '2026-07-02', 'ÖDENDİ', 'Gider türü orijinal kayıtta belirtilmemiş, lütfen tamamlayın');

-- Personel (Zeytinkule) — isim alani bos birakildi, uygulamadan kisi bazinda doldurulabilir
insert into staff (id, isletme_id, isim, gorev, aylik_ucret) values
(1, 1, NULL, 'Gece Güvenlik', 85000),
(2, 1, NULL, 'Gündüz Güvenlik', NULL),
(3, 1, NULL, 'Ara Personel', NULL),
(4, 1, NULL, 'Temizlik Personeli', NULL),
(5, 1, NULL, 'Yönetim Asistanı', NULL),
(6, 1, NULL, 'Yönetici', NULL);
select setval(pg_get_serial_sequence('staff','id'), 6, true);

-- Personel maaş ödemeleri (bilinen)
insert into staff_payments (staff_id, ay, tarih, durum) values
(1, '2026-06', NULL, 'Bilinmiyor'),
(1, '2026-07', '2026-07-11', 'ÖDENDİ'),
(1, '2026-08', NULL, 'Bilinmiyor'),
(6, '2026-07', '2026-07-11', 'ÖDENDİ');

-- Bakim kalemleri baslangicta bos - uygulama icinden eklenecek
-- Ofis/İnşaat gibi yeni işletmeler uygulama içinden ('+ Yeni İşletme Ekle') eklenecek